convert_model:
  model_filepath: /models/whisper-large-v2
  output_model_filepath: /models/whisper-large-v2-ct2-fp16
  quant: float16

evaluation:
  ct2_model_dir: /models/whisper-large-v2-ct2-fp16
  beam_size: 5
  device: cuda # 'cuda'/'cpu'

manifest_path: /datasets/PORT/set_1_2_test_manifest.json
output_path: pred_manifest.json